// SPDX-License-Identifier: MIT
// Copyright (c) 2024-2026 Andy Brown

#pragma once

#if !defined(SEC_ENABLE_UNICODE_SYMBOL)
#define SEC_ENABLE_UNICODE_SYMBOL false
#endif

#if SEC_ENABLE_UNICODE_SYMBOL

#define SEC_UPPER_ALPHA "\u0391"
#define SEC_UPPER_BETA "\u0392"
#define SEC_UPPER_GAMMA "\u0393"
#define SEC_UPPER_DELTA "\u0394"
#define SEC_UPPER_EPSILON "\u0395"
#define SEC_UPPER_ZETA "\u0396"
#define SEC_UPPER_ETA "\u0397"
#define SEC_UPPER_THETA "\u0398"
#define SEC_UPPER_IOTA "\u0399"
#define SEC_UPPER_KAPPA "\u039A"
#define SEC_UPPER_LAMBDA "\u039B"
#define SEC_UPPER_MU "\u039C"
#define SEC_UPPER_NU "\u039D"
#define SEC_UPPER_XI "\u039E"
#define SEC_UPPER_OMICRON "\u039F"
#define SEC_UPPER_PI "\u03A0"
#define SEC_UPPER_RHO "\u03A1"
#define SEC_UPPER_SIGMA "\u03A3"
#define SEC_UPPER_TAU "\u03A4"
#define SEC_UPPER_UPSILON "\u03A5"
#define SEC_UPPER_PHI "\u03A6"
#define SEC_UPPER_CHI "\u03A7"
#define SEC_UPPER_PSI "\u03A8"
#define SEC_UPPER_OMEGA "\u03A9"

#define SEC_LOWER_ALPHA "\u03B1"
#define SEC_LOWER_BETA "\u03B2"
#define SEC_LOWER_GAMMA "\u03B3"
#define SEC_LOWER_DELTA "\u03B4"
#define SEC_LOWER_EPSILON "\u03B5"
#define SEC_LOWER_ZETA "\u03B6"
#define SEC_LOWER_ETA "\u03B7"
#define SEC_LOWER_THETA "\u03B8"
#define SEC_LOWER_IOTA "\u03B9"
#define SEC_LOWER_KAPPA "\u03BA"
#define SEC_LOWER_LAMBDA "\u03BB"
#define SEC_LOWER_MU "\u03BC"
#define SEC_LOWER_NU "\u03BD"
#define SEC_LOWER_XI "\u03BE"
#define SEC_LOWER_OMICRON "\u03BF"
#define SEC_LOWER_PI "\u03C0"
#define SEC_LOWER_RHO "\u03C1"
#define SEC_LOWER_FINAL_SIGMA "\u03C2"
#define SEC_LOWER_SIGMA "\u03C3"
#define SEC_LOWER_TAU "\u03C4"
#define SEC_LOWER_UPSILON "\u03C5"
#define SEC_LOWER_PHI "\u03C6"
#define SEC_LOWER_CHI "\u03C7"
#define SEC_LOWER_PSI "\u03C8"
#define SEC_LOWER_OMEGA "\u03C9"

#else

#define SEC_UPPER_ALPHA "Alpha"
#define SEC_UPPER_BETA "Beta"
#define SEC_UPPER_GAMMA "Gamma"
#define SEC_UPPER_DELTA "Delta"
#define SEC_UPPER_EPSILON "Epsilon"
#define SEC_UPPER_ZETA "Zeta"
#define SEC_UPPER_ETA "Eta"
#define SEC_UPPER_THETA "Theta"
#define SEC_UPPER_IOTA "Iota"
#define SEC_UPPER_KAPPA "Kappa"
#define SEC_UPPER_LAMBDA "Lambda"
#define SEC_UPPER_MU "Mu"
#define SEC_UPPER_NU "Nu"
#define SEC_UPPER_XI "Xi"
#define SEC_UPPER_OMICRON "Omicron"
#define SEC_UPPER_PI "Pi"
#define SEC_UPPER_RHO "Rho"
#define SEC_UPPER_SIGMA "Sigma"
#define SEC_UPPER_TAU "Tau"
#define SEC_UPPER_UPSILON "Upsilon"
#define SEC_UPPER_PHI "Phi"
#define SEC_UPPER_CHI "Chi"
#define SEC_UPPER_PSI "Psi"
#define SEC_UPPER_OMEGA "Omega"

#define SEC_LOWER_ALPHA "alpha"
#define SEC_LOWER_BETA "beta"
#define SEC_LOWER_GAMMA "gamma"
#define SEC_LOWER_DELTA "delta"
#define SEC_LOWER_EPSILON "epsilon"
#define SEC_LOWER_ZETA "zeta"
#define SEC_LOWER_ETA "eta"
#define SEC_LOWER_THETA "theta"
#define SEC_LOWER_IOTA "iota"
#define SEC_LOWER_KAPPA "kappa"
#define SEC_LOWER_LAMBDA "lambda"
#define SEC_LOWER_MU "mu"
#define SEC_LOWER_NU "nu"
#define SEC_LOWER_XI "xi"
#define SEC_LOWER_OMICRON "omicron"
#define SEC_LOWER_PI "pi"
#define SEC_LOWER_RHO "rho"
#define SEC_LOWER_SIGMA "sigma"
#define SEC_LOWER_FINAL_SIGMA "finalsigma"
#define SEC_LOWER_TAU "tau"
#define SEC_LOWER_UPSILON "upsilon"
#define SEC_LOWER_PHI "phi"
#define SEC_LOWER_CHI "chi"
#define SEC_LOWER_PSI "psi"
#define SEC_LOWER_OMEGA "omega"

#endif


//----------------------------------------------------


#if SEC_ENABLE_UNICODE_SYMBOL

#define SEC_SUP_PLUS_SIGN "\u207A"
#define SEC_SUP_MINUS_SIGN "\u207B"
#define SEC_SUP_EQUALS_SIGN "\u207C"
#define SEC_SUP_LEFT_PARENTHESIS "\u207D"
#define SEC_SUP_RIGHT_PARENTHESIS "\u207E"

#define SEC_SUP_ZERO "\u2070"
#define SEC_SUP_ONE "\u00B9"
#define SEC_SUP_TWO "\u00B2"
#define SEC_SUP_THREE "\u00B3"
#define SEC_SUP_FOUR "\u2074"
#define SEC_SUP_FIVE "\u2075"
#define SEC_SUP_SIX "\u2076"
#define SEC_SUP_SEVEN "\u2077"
#define SEC_SUP_EIGHT "\u2078"
#define SEC_SUP_NINE "\u2079"

#define SEC_SUB_PLUS_SIGN "\u208A"
#define SEC_SUB_MINUS_SIGN "\u208B"
#define SEC_SUB_EQUALS_SIGN "\u208C"
#define SEC_SUB_LEFT_PARENTHESIS "\u208D"
#define SEC_SUB_RIGHT_PARENTHESIS "\u208E"

#define SEC_SUB_ZERO "\u2080"
#define SEC_SUB_ONE "\u2081"
#define SEC_SUB_TWO "\u2082"
#define SEC_SUB_THREE "\u2083"
#define SEC_SUB_FOUR "\u2084"
#define SEC_SUB_FIVE "\u2085"
#define SEC_SUB_SIX "\u2086"
#define SEC_SUB_SEVEN "\u2087"
#define SEC_SUB_EIGHT "\u2088"
#define SEC_SUB_NINE "\u2089"

#define SEC_SUP_LOWER_A "\u1D43"
#define SEC_SUP_LOWER_B "\u1D47"
#define SEC_SUP_LOWER_C "\u1D9C"
#define SEC_SUP_LOWER_D "\u1D48"
#define SEC_SUP_LOWER_E "\u1D49"
#define SEC_SUP_LOWER_F "\u1DA0"
#define SEC_SUP_LOWER_G "\u1D4D"
#define SEC_SUP_LOWER_H "\u02B0"
#define SEC_SUP_LOWER_I "\u2071"
#define SEC_SUP_LOWER_J "\u02B2"
#define SEC_SUP_LOWER_K "\u1D4F"
#define SEC_SUP_LOWER_L "\u02E1"
#define SEC_SUP_LOWER_M "\u1D50"
#define SEC_SUP_LOWER_N "\u207F"
#define SEC_SUP_LOWER_O "\u1D52"
#define SEC_SUP_LOWER_P "\u1D56"
#define SEC_SUP_LOWER_R "\u02B3"
#define SEC_SUP_LOWER_S "\u02E2"
#define SEC_SUP_LOWER_T "\u1D57"
#define SEC_SUP_LOWER_U "\u1DB8"
#define SEC_SUP_LOWER_V "\u1D5F"
#define SEC_SUP_LOWER_W "\u02B7"
#define SEC_SUP_LOWER_X "\u02E3"
#define SEC_SUP_LOWER_Y "\u02B8"
#define SEC_SUP_LOWER_Z "\u1DBB"

#define SEC_SUB_LOWER_A "\u2090"
#define SEC_SUB_LOWER_E "\u2091"
#define SEC_SUB_LOWER_O "\u2092"
#define SEC_SUB_LOWER_X "\u2093"
#define SEC_SUB_LOWER_H "\u2095"
#define SEC_SUB_LOWER_K "\u2096"
#define SEC_SUB_LOWER_L "\u2097"
#define SEC_SUB_LOWER_M "\u2098"
#define SEC_SUB_LOWER_N "\u2099"
#define SEC_SUB_LOWER_P "\u209A"
#define SEC_SUB_LOWER_S "\u209B"
#define SEC_SUB_LOWER_T "\u209C"
#define SEC_SUB_LOWER_I "\u1D62"
#define SEC_SUB_LOWER_R "\u1D63"
#define SEC_SUB_LOWER_U "\u1D64"
#define SEC_SUB_LOWER_V "\u1D65"

#else

#define SEC_SUP_PLUS_SIGN "^+"
#define SEC_SUP_MINUS_SIGN "^-"
#define SEC_SUP_EQUALS_SIGN "^="
#define SEC_SUP_LEFT_PARENTHESIS "^("
#define SEC_SUP_RIGHT_PARENTHESIS "^)"

#define SEC_SUP_ZERO "^0"
#define SEC_SUP_ONE "^1"
#define SEC_SUP_TWO "^2"
#define SEC_SUP_THREE "^3"
#define SEC_SUP_FOUR "^4"
#define SEC_SUP_FIVE "^5"
#define SEC_SUP_SIX "^6"
#define SEC_SUP_SEVEN "^7"
#define SEC_SUP_EIGHT "^8"
#define SEC_SUP_NINE "^9"

#define SEC_SUB_PLUS_SIGN "_+"
#define SEC_SUB_MINUS_SIGN "_-"
#define SEC_SUB_EQUALS_SIGN "_="
#define SEC_SUB_LEFT_PARENTHESIS "_("
#define SEC_SUB_RIGHT_PARENTHESIS "_)"

#define SEC_SUB_ZERO "_0"
#define SEC_SUB_ONE "_1"
#define SEC_SUB_TWO "_2"
#define SEC_SUB_THREE "_3"
#define SEC_SUB_FOUR "_4"
#define SEC_SUB_FIVE "_5"
#define SEC_SUB_SIX "_6"
#define SEC_SUB_SEVEN "_7"
#define SEC_SUB_EIGHT "_8"
#define SEC_SUB_NINE "_9"

#define SEC_SUP_LOWER_A "^a"
#define SEC_SUP_LOWER_B "^b"
#define SEC_SUP_LOWER_C "^c"
#define SEC_SUP_LOWER_D "^d"
#define SEC_SUP_LOWER_E "^e"
#define SEC_SUP_LOWER_F "^f"
#define SEC_SUP_LOWER_G "^g"
#define SEC_SUP_LOWER_H "^h"
#define SEC_SUP_LOWER_I "^i"
#define SEC_SUP_LOWER_J "^j"
#define SEC_SUP_LOWER_K "^k"
#define SEC_SUP_LOWER_L "^l"
#define SEC_SUP_LOWER_M "^m"
#define SEC_SUP_LOWER_N "^n"
#define SEC_SUP_LOWER_O "^o"
#define SEC_SUP_LOWER_P "^p"
#define SEC_SUP_LOWER_R "^r"
#define SEC_SUP_LOWER_S "^s"
#define SEC_SUP_LOWER_T "^t"
#define SEC_SUP_LOWER_U "^u"
#define SEC_SUP_LOWER_V "^v"
#define SEC_SUP_LOWER_W "^w"
#define SEC_SUP_LOWER_X "^x"
#define SEC_SUP_LOWER_Y "^y"
#define SEC_SUP_LOWER_Z "^z"

#define SEC_SUB_LOWER_A "_a"
#define SEC_SUB_LOWER_E "_e"
#define SEC_SUB_LOWER_O "_o"
#define SEC_SUB_LOWER_X "_x"
#define SEC_SUB_LOWER_H "_h"
#define SEC_SUB_LOWER_K "_k"
#define SEC_SUB_LOWER_L "_l"
#define SEC_SUB_LOWER_M "_m"
#define SEC_SUB_LOWER_N "_n"
#define SEC_SUB_LOWER_P "_p"
#define SEC_SUB_LOWER_S "_s"
#define SEC_SUB_LOWER_T "_t"
#define SEC_SUB_LOWER_I "_i"
#define SEC_SUB_LOWER_R "_r"
#define SEC_SUB_LOWER_U "_u"
#define SEC_SUB_LOWER_V "_v"

#endif


//----------------------------------------------------


#if SEC_ENABLE_UNICODE_SYMBOL

#define SEC_ANGSTROM "\u212B"
#define SEC_OHM SEC_UPPER_OMEGA

#define SEC_SUM_SIGN "\u03A3"
#define SEC_DIFF_SIGN SEC_UPPER_DELTA

#define SEC_LESS_THAN_OR_EQUAL_TO "\u2264"
#define SEC_GREATER_THAN_OR_EQUAL_TO "\u2265"
#define SEC_MUCH_LESS_THAN "\u226A"
#define SEC_MUCH_GREATER_THAN "\u226B"
#define SEC_MULTIPLICATION_SIGN "\u00D7"
#define SEC_PLUS_MINUS_SIGN "\u00B1"
#define SEC_DIVISION_SIGN "\u00F7"

#else

#define SEC_ANGSTROM "Angstrom"
#define SEC_OHM "Ohm"

#define SEC_SUM_SIGN "Sum"
#define SEC_DIFF_SIGN "Diff"

#define SEC_LESS_THAN_OR_EQUAL_TO "<="
#define SEC_GREATER_THAN_OR_EQUAL_TO ">="
#define SEC_MUCH_LESS_THAN "<<"
#define SEC_MUCH_GREATER_THAN ">>"
#define SEC_MULTIPLICATION_SIGN "x"
#define SEC_PLUS_MINUS_SIGN "PlusMinus"
#define SEC_DIVISION_SIGN "/"

#endif
